/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import <Foundation/NSCoder.h>

struct _VMURange {
    unsigned long long location;
    unsigned long long length;
};

@interface VMUAddressRange : NSObject <NSCoding>
{
    struct _VMURange _addressRange;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

