/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "VMUAddressRange.h"

@interface VMUSourceInfo : VMUAddressRange <NSCopying>
{
    NSString *_path;
    unsigned int _lineNumber;
    unsigned int _fileOffset;
}

+ (id)sourceInfoWithPath:(id)arg1 addressRange:(struct _VMURange)arg2 lineNumber:(unsigned int)arg3 fileOffset:(unsigned int)arg4;
- (id)initWithPath:(id)arg1 addressRange:(struct _VMURange)arg2 lineNumber:(unsigned int)arg3 fileOffset:(unsigned int)arg4;
- (NSString *)path;
- (NSString *)fileName;
- (unsigned int)lineNumber;
- (unsigned int)fileOffset;
- (struct _VMURange)addressRange;
- (long long)compare:(id)arg1;
- (BOOL)isEqualToSourceInfo:(id)arg1;
- (NSString *)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

