/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "VMUMemory-Protocol.h"

@class NSArray, NSDictionary, NSString;

@interface VMUSymbolOwner : NSObject <NSCopying>
{
    NSString *_name;
    NSDictionary *_signature;
    id <VMUMemory> _textMemory;
    NSArray *_regions;
    NSArray *_symbols;
    NSArray *_sourceInfos;
    unsigned int _flags;
    unsigned int _currentVersion;
    unsigned int _compatibilityVersion;
}

+ (id)symbolOwnerWithName:(id)arg1 signature:(id)arg2 textMemory:(id)arg3 regions:(id)arg4 symbols:(id)arg5 sourceInfos:(id)arg6 flags:(unsigned int)arg7 currentVersion:(unsigned int)arg8 compatibilityVersion:(unsigned int)arg9;
- (id)initWithName:(id)arg1 signature:(id)arg2 textMemory:(id)arg3 regions:(id)arg4 symbols:(id)arg5 sourceInfos:(id)arg6 flags:(unsigned int)arg7 currentVersion:(unsigned int)arg8 compatibilityVersion:(unsigned int)arg9;
- (NSString *)name;
- (id)signature;
- (NSString *)path;
- (id)architecture;
- (BOOL)containsAddress:(unsigned long long)arg1;
- (id)regions;
- (id)regionsForName:(id)arg1;
- (id)regionForAddress:(unsigned long long)arg1;
- (id)symbolForAddress:(unsigned long long)arg1;
- (id)symbolsForName:(id)arg1;
- (id)symbolForName:(id)arg1;
- (id)symbolsForMangledName:(id)arg1;
- (id)sourceInfoForAddress:(unsigned long long)arg1;
- (id)symbols;
- (id)sourceInfos;
- (id)symbolsInAddressRange:(struct _VMURange)arg1;
- (id)sourceInfosInAddressRange:(struct _VMURange)arg1;
- (unsigned int)flags;
- (unsigned int)currentVersion;
- (unsigned int)compatibilityVersion;
- (BOOL)isMachO;
- (BOOL)isProtected;
- (BOOL)isPEF;
- (BOOL)isCommpage;
- (BOOL)isAOut;
- (BOOL)isDylib;
- (BOOL)isDyld;
- (BOOL)isBundle;
- (BOOL)isDsym;
- (BOOL)isEqualToSymbolOwner:(id)arg1;
- (long long)compare:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

