        "(function(){var e,t=this,n=function(){e=new r};Object.defineProperty(t"
        ",\"recv\",{enumerable:!0,value:function(){var t,n;return 1===arguments"
        ".length?(t=\"*\",n=arguments[0]):(t=arguments[0],n=arguments[1]),e.reg"
        "isterCallback(t,n)}}),Object.defineProperty(t,\"send\",{enumerable:!0,"
        "value:function(e,n){var r={type:\"send\",payload:e};t._send(JSON.strin"
        "gify(r),n||null)}}),Object.defineProperty(t,\"ptr\",{enumerable:!0,val"
        "ue:function(e){return new NativePointer(e)}}),Object.defineProperty(t,"
        "\"NULL\",{enumerable:!0,value:new NativePointer(\"0\")}),Object.define"
        "Property(Memory,\"dup\",{enumerable:!0,value:function(e,t){var n=Memor"
        "y.alloc(t);return Memory.copy(n,e,t),n}});var r=function(){var e=[],n="
        "{},r=function(){t._setIncomingMessageCallback(i)};this.registerCallbac"
        "k=function(e,t){var r=new a(t);return n[e]=r[1],o(),r[0]};var i=functi"
        "on(t){e.push(JSON.parse(t)),o()},o=function(){e.splice(0,e.length).for"
        "Each(l)},l=function(t){var r;if(n.hasOwnProperty(t.type))r=t.type;else"
        "{if(!n.hasOwnProperty(\"*\"))return void e.push(t);r=\"*\"}var a=n[r];"
        "delete n[r],a(t)};r.call(this)},a=function(e){var n=!1;this.wait=funct"
        "ion(){for(;!n;)t._waitForEvent()};var r=function(t){e(t),n=!0};return["
        "this,r]};n.call(this)}).call(this),function(){var _runtime=null,_api=n"
        "ull,pointerSize=Process.pointerSize,scratchBuffer=Memory.alloc(pointer"
        "Size);Object.defineProperty(this,\"ObjC\",{enumerable:!0,get:function("
        "){return null===_runtime&&(_runtime=new Runtime),_runtime}});var Runti"
        "me=function(){var e=null,t=null,n=[],r=function(){e=getApi(),null!==e&"
        "&(t=new ClassFactory)};Object.defineProperty(this,\"available\",{enume"
        "rable:!0,get:function(){return null!==e}}),Object.defineProperty(this,"
        "\"classes\",{enumerable:!0,get:function(){return t.classes}}),Object.d"
        "efineProperty(this,\"mainQueue\",{enumerable:!0,get:function(){return "
        "e._dispatch_main_q}}),this.schedule=function(t,r){var a=this.use(\"NSA"
        "utoreleasePool\"),i=new NativeCallback(function(){var e=a.alloc().init"
        "(),t=null;try{r()}catch(e){t=e}if(e.release(),setTimeout(function(){n."
        "splice(n.indexOf(i),1)},0),null!==t)throw t},\"void\",[\"pointer\"]);n"
        ".push(i),e.dispatch_async_f(t,NULL,i)},this.use=function(e){return t.u"
        "se(e)},this.cast=function(e,n){return t.cast(e,n)},this.implement=func"
        "tion(e,t){return new NativeCallback(t,e.returnType,e.argumentTypes)},t"
        "his.refreshClasses=function(){t.refresh()},this.selector=function(t){r"
        "eturn e.sel_registerName(Memory.allocUtf8String(t))},this.selectorAsSt"
        "ring=function(t){return Memory.readUtf8String(e.sel_getName(t))},r.cal"
        "l(this)},ClassFactory=function ClassFactory(){var factory=this,classNa"
        "mes=[],templateByName={},classByHandle={},msgSendBySignatureId={},api="
        "null,initialize=function(){api=getApi(),this.refresh()};Object.defineP"
        "roperty(this,\"classes\",{enumerable:!0,get:function(){return classNam"
        "es}}),this.use=function(e){var t=templateByName[e];if(!t)throw new Err"
        "or(\"Cannot find class '\"+e+\"'\");if(null===t[1]){var n=ensureClass("
        "t[0],e);t[1]=new n(t[0],null)}return t[1]},this.cast=function(e,t){var"
        " n=t.classHandle,r=classByHandle[n];return new r(n,e)},this.refresh=fu"
        "nction(){var e=api.objc_getClassList(NULL,0),t=Memory.alloc(e*pointerS"
        "ize);e=api.objc_getClassList(t,e);for(var n=0,r=0;r!==e;r++){n++;var a"
        "=Memory.readPointer(t.add(r*pointerSize)),i=Memory.readUtf8String(api."
        "class_getName(a));templateByName.hasOwnProperty(i)||(templateByName[i]"
        "=[a,null],classNames.push(i))}};var ensureClass=function ensureClass(c"
        "lassHandle,cachedName){var handleId=classHandle.toString(),klass=class"
        "ByHandle[handleId];if(klass)return klass;var name=null!==cachedName?ca"
        "chedName:Memory.readUtf8String(api.class_getName(classHandle)),superHa"
        "ndle=api.class_getSuperclass(classHandle),superKlass=superHandle.isNul"
        "l()?null:ensureClass(superHandle,null);eval(\"klass = function \"+name"
        "+\"(ch, handle) {\"+(null!==superKlass?\"superKlass.call(this, ch || c"
        "lassHandle, handle);\":\"this.classHandle = ch || classHandle; this.ha"
        "ndle = handle || NULL;\")+\"initialize(ch, handle);};\");var initializ"
        "e=function(){},initializeClass=function(){klass.prototype.toString=fun"
        "ction(){return this.description().UTF8String()},addMethods(\"+\"),addM"
        "ethods(\"-\")},addMethods=function(e){for(var t=api.class_copyMethodLi"
        "st(\"+\"===e?api.object_getClass(classHandle):classHandle,scratchBuffe"
        "r),n=Memory.readU32(scratchBuffer),r=0;r!==n;r++)addMethod(Memory.read"
        "Pointer(t.add(r*pointerSize)),e);api.free(t)},addMethod=function addMe"
        "thod(m,type){try{var sel=api.method_getName(m),name=Memory.readUtf8Str"
        "ing(api.sel_getName(sel)),jsName=jsMethodName(name),signature=parseSig"
        "nature(Memory.readUtf8String(api.method_getTypeEncoding(m))),retType=s"
        "ignature.retType,argTypes=signature.argTypes.slice(2),objc_msgSend=get"
        "MsgSendImpl(signature),argVariableNames=argTypes.map(function(e,t){ret"
        "urn\"a\"+(t+1)}),callArgs=[\"+\"===type?\"this.classHandle\":\"this.ha"
        "ndle\",\"sel\"].concat(argTypes.map(function(e,t){return e.toNative?\""
        "argTypes[\"+t+\"].toNative.call(this, \"+argVariableNames[t]+\")\":arg"
        "VariableNames[t]})),returnCaptureLeft,returnCaptureRight;\"void\"===re"
        "tType.type?(returnCaptureLeft=\"\",returnCaptureRight=\"\"):retType.fr"
        "omNative?(returnCaptureLeft=\"return retType.fromNative.call(this, \","
        "returnCaptureRight=\")\"):(returnCaptureLeft=\"return \",returnCapture"
        "Right=\"\"),eval(\"var f = function (\"+argVariableNames.join(\", \")+"
        "\") { \"+returnCaptureLeft+\"objc_msgSend(\"+callArgs.join(\", \")+\")"
        "\"+returnCaptureRight+\"; }\"),klass.prototype[jsName]=f,Object.define"
        "Property(f,\"selector\",{enumerable:!0,value:sel});var implementation="
        "null;Object.defineProperty(f,\"implementation\",{enumerable:!0,get:fun"
        "ction(){return new NativeFunction(api.method_getImplementation(m),f.re"
        "turnType,f.argumentTypes)},set:function(e){implementation=e,api.method"
        "_setImplementation(m,e)}}),Object.defineProperty(f,\"returnType\",{enu"
        "merable:!0,value:retType.type}),Object.defineProperty(f,\"argumentType"
        "s\",{enumerable:!0,value:signature.argTypes.map(function(e){return e.t"
        "ype})})}catch(e){}},jsMethodName=function(e){for(var t=\"\",n=0;n!==e."
        "length;n++){var r=e.charAt(n);t+=\":\"===r?\"_\":r}return t},parseSign"
        "ature=function(e){var t=\"\",n=nextType(e),r=parseType(n[0]);t+=r.type"
        ";for(var a=[];n[1].length>0;){n=nextType(n[1]);var i=parseType(n[0]);t"
        "+=i.type,a.push(i)}return{id:t,retType:r,argTypes:a}},parseType=functi"
        "on(e){for(var t=[];e.length>0;){var n=qualifierById[e[0]];if(!n)break;"
        "t.push(n),e=e.substring(1)}var r=converterById[simplifyType(e)];if(!r)"
        "throw new Error(\"No parser for type \"+e);return r},simplifyType=func"
        "tion(e){if(\"^\"===e[0])switch(e[1]){case\"[\":case\"{\":case\"(\":ret"
        "urn e.substring(0,2)+e.substring(e.length-1)}return e},nextType=functi"
        "on(e){for(var t=\"\",n=0,r=null,a=0,i=!1;n<e.length;){var o=e[n];if(nu"
        "ll!==r)t+=o,o===r[0]?a++:o===r[1]&&(a--,0===a&&(r=null));else{var l=e."
        "charCodeAt(n),s=l>=48&&57>=l;if(i){if(!s)break}else i=s,s||(t+=e[n],\""
        "[\"===o?(r=\"[]\",a=1):\"{\"===o?(r=\"{}\",a=1):\"(\"===o&&(r=\"()\",a"
        "=1))}n++}return[t,e.substring(n)]},qualifierById={r:\"const\",n:\"in\""
        ",N:\"inout\",o:\"out\",O:\"bycopy\",R:\"byref\",V:\"oneway\"},converte"
        "rById={c:{type:\"char\",fromNative:function(e){return e?!0:!1},toNativ"
        "e:function(e){return e?1:0}},i:{type:\"int\"},q:{type:\"int64\"},C:{ty"
        "pe:\"uchar\"},I:{type:\"uint\"},S:{type:\"uint16\"},Q:{type:\"uint64\""
        "},f:{type:\"float\"},d:{type:\"double\"},v:{type:\"void\"},\"*\":{type"
        ":\"pointer\",fromNative:function(e){return e.isNull()?null:Memory.read"
        "Utf8String(e)}},\"@\":{type:\"pointer\",fromNative:function(e){if(e.is"
        "Null())return null;if(e.toString(16)===this.handle.toString(16))return"
        " this;var t=api.object_getClass(e),n=ensureClass(t,null);return new n("
        "t,e)},toNative:function(e){return\"string\"==typeof e?factory.use(\"NS"
        "String\").stringWithUTF8String_(Memory.allocUtf8String(e)).handle:e}},"
        "\"@?\":{type:\"pointer\"},\"#\":{type:\"pointer\"},\":\":{type:\"point"
        "er\"},\"^i\":{type:\"pointer\"},\"^q\":{type:\"pointer\"},\"^S\":{type"
        ":\"pointer\"},\"^^S\":{type:\"pointer\"},\"^Q\":{type:\"pointer\"},\"^"
        "v\":{type:\"pointer\"},\"^*\":{type:\"pointer\"},\"^@\":{type:\"pointe"
        "r\"},\"^?\":{type:\"pointer\"},\"^{}\":{type:\"pointer\"}};if(null!==s"
        "uperKlass){var Surrogate=function(){this.constructor=klass};Surrogate."
        "prototype=superKlass.prototype,klass.prototype=new Surrogate,klass.__n"
        "ame__=name,klass.__super__=superKlass.prototype}return initializeClass"
        "(),classByHandle[handleId]=klass,klass},getMsgSendImpl=function(e){var"
        " t=msgSendBySignatureId[e.id];if(!t){var n=[];e.argTypes.forEach(funct"
        "ion(e,t){n.push(e.type),1==t&&n.push(\"...\")}),t=new NativeFunction(a"
        "pi.objc_msgSend,e.retType.type,n),msgSendBySignatureId[e.id]=t}return "
        "t};initialize.call(this)},getApi=function(){if(null!==_api)return _api"
        ";var e={},t=[{module:\"libsystem_malloc.dylib\",functions:{free:[\"voi"
        "d\",[\"pointer\"]]},variables:{}},{module:\"libobjc.A.dylib\",function"
        "s:{objc_msgSend:function(e){this.objc_msgSend=e,this.objc_msgSend_noar"
        "gs=new NativeFunction(e,\"pointer\",[\"pointer\",\"pointer\",\"...\"])"
        "},objc_getClassList:[\"int\",[\"pointer\",\"int\"]],class_getName:[\"p"
        "ointer\",[\"pointer\"]],class_copyMethodList:[\"pointer\",[\"pointer\""
        ",\"pointer\"]],class_getSuperclass:[\"pointer\",[\"pointer\"]],object_"
        "getClass:[\"pointer\",[\"pointer\"]],method_getName:[\"pointer\",[\"po"
        "inter\"]],method_getTypeEncoding:[\"pointer\",[\"pointer\"]],method_ge"
        "tImplementation:[\"pointer\",[\"pointer\"]],method_setImplementation:["
        "\"pointer\",[\"pointer\",\"pointer\"]],sel_getName:[\"pointer\",[\"poi"
        "nter\"]],sel_registerName:[\"pointer\",[\"pointer\"]]},variables:{}},{"
        "module:\"libdispatch.dylib\",functions:{dispatch_async_f:[\"void\",[\""
        "pointer\",\"pointer\",\"pointer\"]]},variables:{_dispatch_main_q:funct"
        "ion(e){this._dispatch_main_q=e}}}],n=0;return t.forEach(function(t){va"
        "r r=t.functions,a=t.variables;n+=Object.keys(r).length+Object.keys(a)."
        "length,Module.enumerateExports(t.module,{onMatch:function(t){var i=t.n"
        "ame;if(\"function\"===t.type){var o=r[i];o&&(\"function\"==typeof o?o."
        "call(e,t.address):e[i]=new NativeFunction(t.address,o[0],o[1]),delete "
        "r[i],n--)}else if(\"variable\"===t.type){var l=a[i];l&&(l.call(e,t.add"
        "ress),delete a[i],n--)}return 0===n?\"stop\":void 0},onComplete:functi"
        "on(){}})}),0===n&&(_api=e),_api}}.call(this),function(){function Env(e"
        "){this.handle=e}var _runtime=null,_api=null,pointerSize=Process.pointe"
        "rSize,scratchBuffer=Memory.alloc(pointerSize),JNI_OK=0,JNI_VERSION_1_6"
        "=65542,CONSTRUCTOR_METHOD=1,STATIC_METHOD=2,INSTANCE_METHOD=3,JNI_ENV_"
        "OFFSET_SELF=12,CLASS_OBJECT_SIZE=160,CLASS_OBJECT_OFFSET_VTABLE_COUNT="
        "112,CLASS_OBJECT_OFFSET_VTABLE=116,OBJECT_OFFSET_CLAZZ=0,METHOD_SIZE=5"
        "6,METHOD_OFFSET_CLAZZ=0,METHOD_OFFSET_ACCESS_FLAGS=4,METHOD_OFFSET_MET"
        "HOD_INDEX=8,METHOD_OFFSET_REGISTERS_SIZE=10,METHOD_OFFSET_OUTS_SIZE=12"
        ",METHOD_OFFSET_INS_SIZE=14,METHOD_OFFSET_INSNS=32,METHOD_OFFSET_JNI_AR"
        "G_INFO=36;Object.defineProperty(this,\"Dalvik\",{enumerable:!0,get:fun"
        "ction(){return null===_runtime&&(_runtime=new Runtime),_runtime}});var"
        " Runtime=function e(){var t=null,n=null,r=null,a=[],i=function(){t=get"
        "Api(),null!==t&&(n=new VM(t),r=new ClassFactory(t,n))};WeakRef.bind(e,"
        "function(){null!==t&&n.perform(function(){var e=n.getEnv();r.dispose(e"
        "),Env.dispose(e)})}),Object.defineProperty(this,\"available\",{enumera"
        "ble:!0,get:function(){return null!==t}}),this.perform=function(e){if(n"
        "ull===t)throw new Error(\"Dalvik runtime not available\");null!==r.loa"
        "der?n.perform(e):(a.push(e),1===a.length&&n.perform(function(){var e=r"
        ".use(\"android.app.ActivityThread\"),t=r.use(\"android.os.Handler\"),i"
        "=r.use(\"android.os.Looper\"),o=i.getMainLooper(),l=t.$new.overload(\""
        "android.os.Looper\").call(t,o),s=l.obtainMessage();t.dispatchMessage.i"
        "mplementation=function(i){var o=this.$isSameObject(l);if(o){var s=e.cu"
        "rrentApplication();if(null!==s){t.dispatchMessage.implementation=null;"
        "var u=s.getClassLoader();setTimeout(function(){r.loader=u,a.forEach(n."
        "perform,n),a=null},0)}}else this.dispatchMessage(i)},s.sendToTarget()}"
        "))},this.use=function(e){if(null===r.loader)throw new Error(\"Not allo"
        "wed outside Dalvik.perform() callback\");return r.use(e)},this.cast=fu"
        "nction(e,t){return r.cast(e,t)},i.call(this)},ClassFactory=function Cl"
        "assFactory(api,vm){var factory=this,classes={},patchedClasses={},loade"
        "r=null,initialize=function(){api=getApi()};this.dispose=function(e){fo"
        "r(var t in patchedClasses)if(patchedClasses.hasOwnProperty(t)){var n=p"
        "atchedClasses[t];Memory.writePointer(n.vtablePtr,n.vtable),Memory.writ"
        "eS32(n.vtableCountPtr,n.vtableCount);for(var r in n.targetMethods)n.ta"
        "rgetMethods.hasOwnProperty(r)&&(n.targetMethods[r].implementation=null"
        ")}patchedClasses={};for(var a in classes)if(classes.hasOwnProperty(a))"
        "{var i=classes[a];e.deleteGlobalRef(i.__handle__)}classes={}},Object.d"
        "efineProperty(this,\"loader\",{enumerable:!0,get:function(){return loa"
        "der},set:function(e){loader=e}}),this.use=function(e){var t=classes[e]"
        ";if(!t){var n=vm.getEnv();if(null!==loader){var r=loader.loadClass(e);"
        "t=ensureClass(r.$handle,e)}else{var a=n.findClass(e.replace(/\\./g,\"/"
        "\"));t=ensureClass(a,e),n.deleteLocalRef(a)}}return new t(t.__handle__"
        ",null)},this.cast=function(e,t){var n=e.hasOwnProperty(\"$handle\")?e."
        "$handle:e,r=t.$class;return new r(r.__handle__,n)};var ensureClass=fun"
        "ction(classHandle,cachedName){var env=vm.getEnv(),name=null!==cachedNa"
        "me?cachedName:env.getClassName(classHandle),klass=classes[name];if(kla"
        "ss)return klass;var superHandle=env.getSuperclass(classHandle),superKl"
        "ass;superHandle.isNull()?superKlass=null:(superKlass=ensureClass(super"
        "Handle,null),env.deleteLocalRef(superHandle)),eval(\"klass = function "
        "\"+basename(name)+\"(classHandle, handle) {var env = vm.getEnv();this."
        "$class = klass;this.$classHandle = env.newGlobalRef(classHandle);this."
        "$handle = (handle !== null) ? env.newGlobalRef(handle) : null;this.$we"
        "akRef = WeakRef.bind(this, makeHandleDestructor(this.$handle, this.$cl"
        "assHandle));};\"),classes[name]=klass;var initializeClass=function(){k"
        "lass.__name__=name,klass.__handle__=env.newGlobalRef(classHandle),klas"
        "s.prototype.$new=makeConstructor(),klass.prototype.$dispose=dispose,kl"
        "ass.prototype.$isSameObject=function(e){var t=vm.getEnv();return t.isS"
        "ameObject(e.$handle,this.$handle)},addMethods()},dispose=function(){We"
        "akRef.unbind(this.$weakRef)},makeConstructor=function(){for(var e=env."
        "javaLangReflectConstructor(),t=env.method(\"pointer\",[]),n=[],r=objec"
        "tType(name,!1),a=t(env.handle,classHandle,env.javaLangClass().getDecla"
        "redConstructors),i=env.getArrayLength(a),o=0;o!==i;o++){var l=env.getO"
        "bjectArrayElement(a,o),s=env.fromReflectedMethod(l),u=[],p=t(env.handl"
        "e,l,e.getGenericParameterTypes);env.deleteLocalRef(l);var c=env.getArr"
        "ayLength(p);try{for(var d=0;d!==c;d++){var f=env.getObjectArrayElement"
        "(p,d);try{var h=typeFromClassName(env.getTypeName(f));u.push(h)}finall"
        "y{env.deleteLocalRef(f)}}}catch(e){continue}finally{env.deleteLocalRef"
        "(p)}n.push(makeMethod(CONSTRUCTOR_METHOD,s,r,u))}return env.deleteLoca"
        "lRef(a),makeMethodDispatcher(\"<init>\",n)},addMethods=function(){for("
        "var e=env.javaLangReflectMethod(),t=env.javaLangReflectModifier(),n=en"
        "v.method(\"pointer\",[]),r=env.method(\"int32\",[]),a={},i=n(env.handl"
        "e,classHandle,env.javaLangClass().getDeclaredMethods),o=env.getArrayLe"
        "ngth(i),l=0;l!==o;l++){var s=env.getObjectArrayElement(i,l),u=env.from"
        "ReflectedMethod(s),p=n(env.handle,s,e.getName),c=n(env.handle,s,e.getG"
        "enericReturnType),d=n(env.handle,s,e.getGenericParameterTypes),f=r(env"
        ".handle,s,e.getModifiers);env.deleteLocalRef(s);var h,m=env.stringFrom"
        "Jni(p),y=0!==(f&t.STATIC)?STATIC_METHOD:INSTANCE_METHOD,v=[];env.delet"
        "eLocalRef(p);try{h=typeFromClassName(env.getTypeName(c))}catch(e){env."
        "deleteLocalRef(d);continue}finally{env.deleteLocalRef(c)}try{for(var g"
        "=env.getArrayLength(d),b=0;b!==g;b++){var T=env.getObjectArrayElement("
        "d,b);try{var _=typeFromClassName(env.getTypeName(T));v.push(_)}finally"
        "{env.deleteLocalRef(T)}}}catch(e){continue}finally{env.deleteLocalRef("
        "d)}var E;a.hasOwnProperty(m)?E=a[m]:(E=[],a[m]=E),E.push(makeMethod(y,"
        "u,h,v))}for(var S in a)if(a.hasOwnProperty(S)){var C=a[S];if(\"valueOf"
        "\"===S){var O=C.some(function(e){return e.type===INSTANCE_METHOD&&0==="
        "e.argumentTypes.length});if(!O){var M=function(){return this};Object.d"
        "efineProperty(M,\"holder\",{enumerable:!0,value:klass}),Object.defineP"
        "roperty(M,\"type\",{enumerable:!0,value:INSTANCE_METHOD}),Object.defin"
        "eProperty(M,\"returnType\",{enumerable:!0,value:typeFromClassName(\"in"
        "t\")}),Object.defineProperty(M,\"argumentTypes\",{enumerable:!0,value:"
        "[]}),Object.defineProperty(M,\"canInvokeWith\",{enumerable:!0,value:fu"
        "nction(e){return 0===e.length}}),C.push(M)}}klass.prototype[S]=makeMet"
        "hodDispatcher(S,C)}},makeMethodDispatcher=function(e,t){var n={};t.for"
        "Each(function(e){var t=e.argumentTypes.length,r=n[t];r||(r=[],n[t]=r),"
        "r.push(e)});var r=function(){var r=null!==this.$handle;if(t[0].type!=="
        "INSTANCE_METHOD&&r)throw new Error(e+\": cannot call static method by "
        "way of an instance\");if(t[0].type===INSTANCE_METHOD&&!r){if(\"toStrin"
        "g\"===e)return\"<\"+this.$class.__name__+\">\";throw new Error(e+\": c"
        "annot call instance method without an instance\")}var a=n[arguments.le"
        "ngth];if(!a)throw new Error(e+\": argument count does not match any ov"
        "erload\");for(var i=0;i!==a.length;i++){var o=a[i];if(o.canInvokeWith("
        "arguments))return o.apply(this,arguments)}throw new Error(e+\": argume"
        "nt types do not match any overload\")};if(Object.defineProperty(r,\"ov"
        "erloads\",{enumerable:!0,value:t}),Object.defineProperty(r,\"overload"
        "\",{enumerable:!0,value:function(){var t=n[arguments.length];if(!t)thr"
        "ow new Error(e+\": argument count does not match any overload\");for(v"
        "ar r=Array.prototype.join.call(arguments,\":\"),a=0;a!==t.length;a++){"
        "var i=t[a],o=i.argumentTypes.map(function(e){return e.className}).join"
        "(\":\");if(o===r)return i}throw new Error(e+\": specified argument typ"
        "es do not match any overload\")}}),Object.defineProperty(r,\"holder\","
        "{enumerable:!0,get:t[0].holder}),Object.defineProperty(r,\"type\",{enu"
        "merable:!0,value:t[0].type}),1===t.length)Object.defineProperty(r,\"im"
        "plementation\",{enumerable:!0,get:function(){return t[0].implementatio"
        "n},set:function(e){t[0].implementation=e}}),Object.defineProperty(r,\""
        "returnType\",{enumerable:!0,value:t[0].returnType}),Object.definePrope"
        "rty(r,\"argumentTypes\",{enumerable:!0,value:t[0].argumentTypes}),Obje"
        "ct.defineProperty(r,\"canInvokeWith\",{enumerable:!0,value:t[0].canInv"
        "okeWith});else{var a=function(){throw new Error(\"Method has more than"
        " one overload. Please resolve by for example: `method.overload('int')`"
        "\")};Object.defineProperty(r,\"implementation\",{enumerable:!0,get:a,s"
        "et:a}),Object.defineProperty(r,\"returnType\",{enumerable:!0,get:a}),O"
        "bject.defineProperty(r,\"argumentTypes\",{enumerable:!0,get:a}),Object"
        ".defineProperty(r,\"canInvokeWith\",{enumerable:!0,get:a})}return r},m"
        "akeMethod=function(type,methodId,retType,argTypes){var targetMethodId="
        "methodId,originalMethodId=null,rawRetType=retType.type,rawArgTypes=arg"
        "Types.map(function(e){return e.type}),invokeTarget;type==CONSTRUCTOR_M"
        "ETHOD?invokeTarget=env.constructor(rawArgTypes):type==STATIC_METHOD?in"
        "vokeTarget=env.staticMethod(rawRetType,rawArgTypes):type==INSTANCE_MET"
        "HOD&&(invokeTarget=env.method(rawRetType,rawArgTypes));var frameCapaci"
        "ty=2,argVariableNames=argTypes.map(function(e,t){return\"a\"+(t+1)}),c"
        "allArgs=[\"env.handle\",type===INSTANCE_METHOD?\"this.$handle\":\"this"
        ".$classHandle\",\"targetMethodId\"].concat(argTypes.map(function(e,t){"
        "return e.toJni?(frameCapacity++,\"argTypes[\"+t+\"].toJni.call(this, "
        "\"+argVariableNames[t]+\", env)\"):argVariableNames[t]})),returnCaptur"
        "e,returnStatement;\"void\"===rawRetType?(returnCapture=\"\",returnStat"
        "ements=\"env.popLocalFrame(NULL);\"):retType.fromJni?(frameCapacity++,"
        "returnCapture=\"var rawResult = \",returnStatements=\"var result = ret"
        "Type.fromJni.call(this, rawResult, env);env.popLocalFrame(NULL);return"
        " result;\"):(returnCapture=\"var result = \",returnStatements=\"env.po"
        "pLocalFrame(NULL);return result;\"),eval(\"var f = function (\"+argVar"
        "iableNames.join(\", \")+\") {var env = vm.getEnv();if (env.pushLocalFr"
        "ame(\"+frameCapacity+') !== JNI_OK) {env.exceptionClear();throw new Er"
        "ror(\"Out of memory\");}synchronizeVtable.call(this, env);'+returnCapt"
        "ure+\"invokeTarget(\"+callArgs.join(\", \")+\");var throwable = env.ex"
        "ceptionOccurred();if (!throwable.isNull()) {env.exceptionClear();var d"
        "escription = env.method('pointer', [])(env.handle, throwable, env.java"
        "LangObject().toString);var descriptionStr = env.stringFromJni(descript"
        "ion);env.popLocalFrame(NULL);throw new Error(descriptionStr);}\"+retur"
        "nStatements+\"}\"),Object.defineProperty(f,\"holder\",{enumerable:!0,v"
        "alue:klass}),Object.defineProperty(f,\"type\",{enumerable:!0,value:typ"
        "e});var implementation=null,synchronizeVtable=function(e){if(null!==or"
        "iginalMethodId){var t=Memory.readPointer(e.handle.add(JNI_ENV_OFFSET_S"
        "ELF)),n=api.dvmDecodeIndirectRef(t,this.$handle),r=Memory.readPointer("
        "n.add(OBJECT_OFFSET_CLAZZ)),a=r.toString(16),i=patchedClasses[a];if(!i"
        "){var o=r.add(CLASS_OBJECT_OFFSET_VTABLE),l=r.add(CLASS_OBJECT_OFFSET_"
        "VTABLE_COUNT),s=Memory.readPointer(o),u=Memory.readS32(l),p=u*pointerS"
        "ize,c=Memory.alloc(2*p);Memory.copy(c,s,p),Memory.writePointer(o,c),i="
        "{classObject:r,vtablePtr:o,vtableCountPtr:l,vtable:s,vtableCount:u,sha"
        "dowVtable:c,shadowVtableCount:u,targetMethods:{}},patchedClasses[a]=i}"
        "a=methodId.toString(16);var d=i.targetMethods[a];if(!d){var h=i.shadow"
        "VtableCount++;Memory.writePointer(i.shadowVtable.add(h*pointerSize),ta"
        "rgetMethodId),Memory.writeU16(targetMethodId.add(METHOD_OFFSET_METHOD_"
        "INDEX),h),Memory.writeS32(i.vtableCountPtr,i.shadowVtableCount),i.targ"
        "etMethods[a]=f}}};return Object.defineProperty(f,\"implementation\",{e"
        "numerable:!0,get:function(){return implementation},set:function(e){if("
        "null!==e||null!==originalMethodId)if(null===originalMethodId&&(origina"
        "lMethodId=Memory.dup(methodId,METHOD_SIZE),targetMethodId=Memory.dup(m"
        "ethodId,METHOD_SIZE)),null!==e){implementation=implement(f,e);var t=ar"
        "gTypes.reduce(function(e,t){return e+t.size},0);type===INSTANCE_METHOD"
        "&&t++;var n=256|Memory.readU32(methodId.add(METHOD_OFFSET_ACCESS_FLAGS"
        ")),r=t,a=0,i=t,o=2147483648;Memory.writeU32(methodId.add(METHOD_OFFSET"
        "_ACCESS_FLAGS),n),Memory.writeU16(methodId.add(METHOD_OFFSET_REGISTERS"
        "_SIZE),r),Memory.writeU16(methodId.add(METHOD_OFFSET_OUTS_SIZE),a),Mem"
        "ory.writeU16(methodId.add(METHOD_OFFSET_INS_SIZE),i),Memory.writeU32(m"
        "ethodId.add(METHOD_OFFSET_JNI_ARG_INFO),o),api.dvmUseJNIBridge(methodI"
        "d,implementation)}else Memory.copy(methodId,originalMethodId,METHOD_SI"
        "ZE)}}),Object.defineProperty(f,\"returnType\",{enumerable:!0,value:ret"
        "Type}),Object.defineProperty(f,\"argumentTypes\",{enumerable:!0,value:"
        "argTypes}),Object.defineProperty(f,\"canInvokeWith\",{enumerable:!0,va"
        "lue:function(e){return e.length!==argTypes.length?!1:argTypes.every(fu"
        "nction(t,n){return t.isCompatible(e[n])})}}),f};if(null!==superKlass){"
        "var Surrogate=function(){this.constructor=klass};Surrogate.prototype=s"
        "uperKlass.prototype,klass.prototype=new Surrogate,klass.__super__=supe"
        "rKlass.prototype}else klass.__super__=null;return initializeClass(),kl"
        "ass},makeHandleDestructor=function(){var e=Array.prototype.slice.call("
        "arguments).filter(function(e){return null!==e});return function(){vm.p"
        "erform(function(){var t=vm.getEnv();e.forEach(t.deleteGlobalRef,t)})}}"
        ",implement=function(method,fn){var env=vm.getEnv();if(method.hasOwnPro"
        "perty(\"overloads\")){if(method.overloads.length>1)throw new Error(\"M"
        "ethod has more than one overload. Please resolve by for example: `meth"
        "od.overload('int')`\");method=method.overloads[0]}var C=method.holder,"
        "type=method.type,retType=method.returnType,argTypes=method.argumentTyp"
        "es,rawRetType=retType.type,rawArgTypes=argTypes.map(function(e){return"
        " e.type}),frameCapacity=2,argVariableNames=argTypes.map(function(e,t){"
        "return\"a\"+(t+1)}),callArgs=argTypes.map(function(e,t){return e.fromJ"
        "ni?(frameCapacity++,\"argTypes[\"+t+\"].fromJni.call(self, \"+argVaria"
        "bleNames[t]+\", env)\"):argVariableNames[t]}),returnCapture,returnStat"
        "ement,returnNothing;return\"void\"===rawRetType?(returnCapture=\"\",re"
        "turnStatements=\"env.popLocalFrame(NULL);\",returnNothing=\"return;\")"
        ":retType.toJni?(frameCapacity++,returnCapture=\"var result = \",\"poin"
        "ter\"===retType.type?(returnStatements=\"var rawResult = retType.toJni"
        ".call(this, result, env);return env.popLocalFrame(rawResult);\",return"
        "Nothing=\"return NULL;\"):(returnStatements=\"var rawResult = retType."
        "toJni.call(this, result, env);env.popLocalFrame(NULL);return rawResult"
        ";\",returnNothing=\"return 0;\")):(returnCapture=\"var result = \",ret"
        "urnStatements=\"env.popLocalFrame(NULL);return result;\",returnNothing"
        "=\"return 0;\"),eval(\"var f = function (\"+[\"envHandle\",\"thisHandl"
        "e\"].concat(argVariableNames).join(\", \")+\") {var env = new Env(envH"
        "andle);if (env.pushLocalFrame(\"+frameCapacity+\") !== JNI_OK) {return"
        ";}\"+(type===INSTANCE_METHOD?\"var self = new C(C.__handle__, thisHand"
        "le);\":\"var self = new C(thisHandle, null);\")+\"try {\"+returnCaptur"
        "e+\"fn.call(\"+[\"self\"].concat(callArgs).join(\", \")+\");} catch (e"
        ") {if (typeof e === 'object' && e.hasOwnProperty('$handle')) {env.thro"
        "w(e.$handle);\"+returnNothing+\"} else {throw e;}}\"+returnStatements+"
        "\"}\"),Object.defineProperty(f,\"type\",{enumerable:!0,value:type}),Ob"
        "ject.defineProperty(f,\"returnType\",{enumerable:!0,value:retType}),Ob"
        "ject.defineProperty(f,\"argumentTypes\",{enumerable:!0,value:argTypes}"
        "),Object.defineProperty(f,\"canInvokeWith\",{enumerable:!0,value:funct"
        "ion(e){return e.length!==argTypes.length?!1:argTypes.every(function(t,"
        "n){return t.isCompatible(e[n])})}}),new NativeCallback(f,rawRetType,["
        "\"pointer\",\"pointer\"].concat(rawArgTypes))},typeFromClassName=funct"
        "ion(e){var t=types[e];if(!t){if(0===e.indexOf(\"[\"))throw new Error("
        "\"Unsupported type: \"+e);t=objectType(e,!0)}var n={className:e};for(v"
        "ar r in t)t.hasOwnProperty(r)&&(n[r]=t[r]);return n},types={boolean:{t"
        "ype:\"uint8\",size:1,isCompatible:function(e){return\"boolean\"==typeo"
        "f e},fromJni:function(e){return e?!0:!1},toJni:function(e){return e?1:"
        "0}},byte:{type:\"int8\",size:1,isCompatible:function(e){return\"number"
        "\"==typeof e}},char:{type:\"uint16\",size:1,isCompatible:function(e){r"
        "eturn\"string\"==typeof e&&1===e.length},fromJni:function(e){return St"
        "ring.fromCharCode(e)},toJni:function(e){return e.charCodeAt(0)}},short"
        ":{type:\"int16\",size:1,isCompatible:function(e){return\"number\"==typ"
        "eof e}},int:{type:\"int32\",size:1,isCompatible:function(e){return\"nu"
        "mber\"==typeof e}},long:{type:\"int64\",size:2,isCompatible:function(e"
        "){return\"number\"==typeof e}},float:{type:\"float\",size:1,isCompatib"
        "le:function(e){return\"number\"==typeof e}},double:{type:\"double\",si"
        "ze:2,isCompatible:function(e){return\"number\"==typeof e}},void:{type:"
        "\"void\",size:0,isCompatible:function(){return!1}},\"[B\":{type:\"poin"
        "ter\",size:1,isCompatible:function(e){return\"object\"==typeof e&&e.ha"
        "sOwnProperty(\"length\")},fromJni:function(){throw new Error(\"Not yet"
        " implemented ([B)\")},toJni:function(){throw new Error(\"Not yet imple"
        "mented ([B)\")}},\"[C\":{type:\"pointer\",size:1,isCompatible:function"
        "(e){return\"object\"==typeof e&&e.hasOwnProperty(\"length\")},fromJni:"
        "function(){throw new Error(\"Not yet implemented ([C)\")},toJni:functi"
        "on(){throw new Error(\"Not yet implemented ([C)\")}},\"[I\":{type:\"po"
        "inter\",size:1,isCompatible:function(e){return\"object\"==typeof e&&e."
        "hasOwnProperty(\"length\")},fromJni:function(){throw new Error(\"Not y"
        "et implemented ([I)\")},toJni:function(){throw new Error(\"Not yet imp"
        "lemented ([I)\")}},\"[Ljava.lang.String;\":{type:\"pointer\",size:1,is"
        "Compatible:function(e){return\"object\"==typeof e&&e.hasOwnProperty(\""
        "length\")&&(0===e.length||\"string\"==typeof e[0])},fromJni:function(e"
        ",t){for(var n=[],r=t.getArrayLength(e),a=0;a!==r;a++){var i=t.getObjec"
        "tArrayElement(e,a);n.push(t.stringFromJni(i)),t.deleteLocalRef(i)}retu"
        "rn n},toJni:function(e,t){for(var n=t.newObjectArray(e.length,t.javaLa"
        "ngString().handle,NULL),r=0;r!==e.length;r++){var a=t.newStringUtf(e[r"
        "]);t.setObjectArrayElement(n,r,a),t.deleteLocalRef(a)}return n}}},obje"
        "ctType=function(e,t){return{type:\"pointer\",size:1,isCompatible:funct"
        "ion(t){return\"java.lang.String\"===e&&\"string\"==typeof t?!0:\"objec"
        "t\"==typeof t&&t.hasOwnProperty(\"$handle\")},fromJni:function(n,r){re"
        "turn n.isNull()?null:\"java.lang.String\"===e&&t?r.stringFromJni(n):nu"
        "ll!==this.$handle&&r.isSameObject(n,this.$handle)?this:factory.cast(n,"
        "factory.use(e))},toJni:function(e,t){return\"string\"==typeof e?t.newS"
        "tringUtf(e):e.$handle}}};initialize.call(this)},VM=function(e){var t=n"
        "ull,n=null,r=null,a=null,i=function(){t=Memory.readPointer(e.gDvmJni.a"
        "dd(8));var i=Memory.readPointer(t);n=new NativeFunction(Memory.readPoi"
        "nter(i.add(4*pointerSize)),\"int32\",[\"pointer\",\"pointer\",\"pointe"
        "r\"]),r=new NativeFunction(Memory.readPointer(i.add(5*pointerSize)),\""
        "int32\",[\"pointer\"]),a=new NativeFunction(Memory.readPointer(i.add(6"
        "*pointerSize)),\"int32\",[\"pointer\",\"pointer\",\"int32\"])};this.pe"
        "rform=function(e){var t=this.tryGetEnv(),n=null!==t;n||(t=this.attachC"
        "urrentThread());var r=null;try{e()}catch(e){r=e}if(n||this.detachCurre"
        "ntThread(),null!==r)throw r},this.attachCurrentThread=function(){retur"
        "n checkJniResult(\"VM::AttachCurrentThread\",n(t,scratchBuffer,NULL)),"
        "new Env(Memory.readPointer(scratchBuffer))},this.detachCurrentThread=f"
        "unction(){checkJniResult(\"VM::DetachCurrentThread\",r(t))},this.getEn"
        "v=function(){return checkJniResult(\"VM::GetEnv\",a(t,scratchBuffer,JN"
        "I_VERSION_1_6)),new Env(Memory.readPointer(scratchBuffer))},this.tryGe"
        "tEnv=function(){var e=a(t,scratchBuffer,JNI_VERSION_1_6);return e!==JN"
        "I_OK?null:new Env(Memory.readPointer(scratchBuffer))},i.call(this)};!f"
        "unction(){function e(e){return N.push(e),e}function t(){return null==="
        "M&&(M=Memory.readPointer(this.handle)),M}function n(e,n,r,a){var i=nul"
        "l;return function(){null===i&&(i=new NativeFunction(Memory.readPointer"
        "(t.call(this).add(e*pointerSize)),n,r));var o=[i];return o=o.concat.ap"
        "ply(o,arguments),a.apply(this,o)}}var r=28,a=34,i=37,o=40,l=43,s=46,u="
        "49,p=52,c=55,d=58,f=61,h=114,m=117,y=120,v=123,g=126,b=129,T=132,_=135"
        ",E=138,S=141,C={pointer:a,uint8:i,int8:o,uint16:l,int16:s,int32:u,int6"
        "4:p,float:c,double:d,void:f},O={pointer:h,uint8:m,int8:y,uint16:v,int1"
        "6:g,int32:b,int64:T,float:_,double:E,void:S},M=null,N=[];Env.dispose=f"
        "unction(e){N.forEach(e.deleteGlobalRef,e),N=[]},Env.prototype.findClas"
        "s=n(6,\"pointer\",[\"pointer\",\"pointer\"],function(e,t){var n=e(this"
        ".handle,Memory.allocUtf8String(t)),r=this.exceptionOccurred();if(!r.is"
        "Null()){this.exceptionClear();var a=this.method(\"pointer\",[])(this.h"
        "andle,r,this.javaLangObject().toString),i=this.stringFromJni(a);throw "
        "this.deleteLocalRef(a),this.deleteLocalRef(r),new Error(i)}return n}),"
        "Env.prototype.fromReflectedMethod=n(7,\"pointer\",[\"pointer\",\"point"
        "er\"],function(e,t){return e(this.handle,t)}),Env.prototype.getSupercl"
        "ass=n(10,\"pointer\",[\"pointer\",\"pointer\"],function(e,t){return e("
        "this.handle,t)}),Env.prototype.throw=n(13,\"int32\",[\"pointer\",\"poi"
        "nter\"],function(e,t){return e(this.handle,t)}),Env.prototype.exceptio"
        "nOccurred=n(15,\"pointer\",[\"pointer\"],function(e){return e(this.han"
        "dle)}),Env.prototype.exceptionDescribe=n(16,\"void\",[\"pointer\"],fun"
        "ction(e){e(this.handle)}),Env.prototype.exceptionClear=n(17,\"void\",["
        "\"pointer\"],function(e){e(this.handle)}),Env.prototype.pushLocalFrame"
        "=n(19,\"int32\",[\"pointer\",\"int32\"],function(e,t){return e(this.ha"
        "ndle,t)}),Env.prototype.popLocalFrame=n(20,\"pointer\",[\"pointer\",\""
        "pointer\"],function(e,t){return e(this.handle,t)}),Env.prototype.newGl"
        "obalRef=n(21,\"pointer\",[\"pointer\",\"pointer\"],function(e,t){retur"
        "n e(this.handle,t)}),Env.prototype.deleteGlobalRef=n(22,\"void\",[\"po"
        "inter\",\"pointer\"],function(e,t){e(this.handle,t)}),Env.prototype.de"
        "leteLocalRef=n(23,\"void\",[\"pointer\",\"pointer\"],function(e,t){e(t"
        "his.handle,t)}),Env.prototype.isSameObject=n(24,\"uint8\",[\"pointer\""
        ",\"pointer\",\"pointer\"],function(e,t,n){return e(this.handle,t,n)?!0"
        ":!1}),Env.prototype.isInstanceOf=n(32,\"uint8\",[\"pointer\",\"pointer"
        "\",\"pointer\"],function(e,t,n){return e(this.handle,t,n)?!0:!1}),Env."
        "prototype.getMethodId=n(33,\"pointer\",[\"pointer\",\"pointer\",\"poin"
        "ter\",\"pointer\"],function(e,t,n,r){return e(this.handle,t,Memory.all"
        "ocUtf8String(n),Memory.allocUtf8String(r))}),Env.prototype.getFieldId="
        "n(94,\"pointer\",[\"pointer\",\"pointer\",\"pointer\",\"pointer\"],fun"
        "ction(e,t,n,r){return e(this.handle,t,M",
        "emory.allocUtf8String(n),Memory.allocUtf8String(r))}),Env.prototype.ge"
        "tIntField=n(100,\"int32\",[\"pointer\",\"pointer\",\"pointer\"],functi"
        "on(e,t,n){return e(this.handle,t,n)}),Env.prototype.getStaticMethodId="
        "n(113,\"pointer\",[\"pointer\",\"pointer\",\"pointer\",\"pointer\"],fu"
        "nction(e,t,n,r){return e(this.handle,t,Memory.allocUtf8String(n),Memor"
        "y.allocUtf8String(r))}),Env.prototype.getStaticFieldId=n(144,\"pointer"
        "\",[\"pointer\",\"pointer\",\"pointer\",\"pointer\"],function(e,t,n,r)"
        "{return e(this.handle,t,Memory.allocUtf8String(n),Memory.allocUtf8Stri"
        "ng(r))}),Env.prototype.getStaticIntField=n(150,\"int32\",[\"pointer\","
        "\"pointer\",\"pointer\"],function(e,t,n){return e(this.handle,t,n)}),E"
        "nv.prototype.newStringUtf=n(167,\"pointer\",[\"pointer\",\"pointer\"],"
        "function(e,t){var n=Memory.allocUtf8String(t);return e(this.handle,n)}"
        "),Env.prototype.getStringUtfChars=n(169,\"pointer\",[\"pointer\",\"poi"
        "nter\",\"pointer\"],function(e,t){return e(this.handle,t,NULL)}),Env.p"
        "rototype.releaseStringUtfChars=n(170,\"void\",[\"pointer\",\"pointer\""
        ",\"pointer\"],function(e,t,n){e(this.handle,t,n)}),Env.prototype.getAr"
        "rayLength=n(171,\"int32\",[\"pointer\",\"pointer\"],function(e,t){retu"
        "rn e(this.handle,t)}),Env.prototype.newObjectArray=n(172,\"pointer\",["
        "\"pointer\",\"int32\",\"pointer\",\"pointer\"],function(e,t,n,r){retur"
        "n e(this.handle,t,n,r)}),Env.prototype.getObjectArrayElement=n(173,\"p"
        "ointer\",[\"pointer\",\"pointer\",\"int32\"],function(e,t,n){return e("
        "this.handle,t,n)}),Env.prototype.setObjectArrayElement=n(174,\"void\","
        "[\"pointer\",\"pointer\",\"int32\",\"pointer\"],function(e,t,n,r){e(th"
        "is.handle,t,n,r)});var w={},I=function(e,n,r){var a=e+\"|\"+n+\"|\"+r."
        "join(\":\"),i=w[a];return i||(i=new NativeFunction(Memory.readPointer("
        "t.call(this).add(e*pointerSize)),n,[\"pointer\",\"pointer\",\"pointer"
        "\",\"...\"].concat(r)),w[a]=i),i};Env.prototype.constructor=function(e"
        "){return I(r,\"pointer\",e)},Env.prototype.method=function(e,t){var n="
        "C[e];if(void 0===n)throw new Error(\"Unsupported type: \"+e);return I("
        "n,e,t)},Env.prototype.staticMethod=function(e,t){var n=O[e];if(void 0="
        "==n)throw new Error(\"Unsupported type: \"+e);return I(n,e,t)};var j=n"
        "ull;Env.prototype.javaLangClass=function(){if(null===j){var t=this.fin"
        "dClass(\"java/lang/Class\");j={handle:e(this.newGlobalRef(t)),getName:"
        "this.getMethodId(t,\"getName\",\"()Ljava/lang/String;\"),getDeclaredCo"
        "nstructors:this.getMethodId(t,\"getDeclaredConstructors\",\"()[Ljava/l"
        "ang/reflect/Constructor;\"),getDeclaredMethods:this.getMethodId(t,\"ge"
        "tDeclaredMethods\",\"()[Ljava/lang/reflect/Method;\")},this.deleteLoca"
        "lRef(t)}return j};var L=null;Env.prototype.javaLangObject=function(){i"
        "f(null===L){var e=this.findClass(\"java/lang/Object\");L={toString:thi"
        "s.getMethodId(e,\"toString\",\"()Ljava/lang/String;\")},this.deleteLoc"
        "alRef(e)}return L};var F=null;Env.prototype.javaLangReflectConstructor"
        "=function(){if(null===F){var e=this.findClass(\"java/lang/reflect/Cons"
        "tructor\");F={getGenericParameterTypes:this.getMethodId(e,\"getGeneric"
        "ParameterTypes\",\"()[Ljava/lang/reflect/Type;\")},this.deleteLocalRef"
        "(e)}return F};var P=null;Env.prototype.javaLangReflectMethod=function("
        "){if(null===P){var e=this.findClass(\"java/lang/reflect/Method\");P={g"
        "etName:this.getMethodId(e,\"getName\",\"()Ljava/lang/String;\"),getGen"
        "ericParameterTypes:this.getMethodId(e,\"getGenericParameterTypes\",\"("
        ")[Ljava/lang/reflect/Type;\"),getGenericReturnType:this.getMethodId(e,"
        "\"getGenericReturnType\",\"()Ljava/lang/reflect/Type;\"),getModifiers:"
        "this.getMethodId(e,\"getModifiers\",\"()I\")},this.deleteLocalRef(e)}r"
        "eturn P};var R=null;Env.prototype.javaLangReflectModifier=function(){i"
        "f(null===R){var e=this.findClass(\"java/lang/reflect/Modifier\");R={PU"
        "BLIC:this.getStaticIntField(e,this.getStaticFieldId(e,\"PUBLIC\",\"I\""
        ")),PRIVATE:this.getStaticIntField(e,this.getStaticFieldId(e,\"PRIVATE"
        "\",\"I\")),PROTECTED:this.getStaticIntField(e,this.getStaticFieldId(e,"
        "\"PROTECTED\",\"I\")),STATIC:this.getStaticIntField(e,this.getStaticFi"
        "eldId(e,\"STATIC\",\"I\"))},this.deleteLocalRef(e)}return R};var A=nul"
        "l;Env.prototype.javaLangReflectGenericArrayType=function(){if(null===A"
        "){var t=this.findClass(\"java/lang/reflect/GenericArrayType\");A={hand"
        "le:e(this.newGlobalRef(t)),getGenericComponentType:this.getMethodId(t,"
        "\"getGenericComponentType\",\"()Ljava/lang/reflect/Type;\")},this.dele"
        "teLocalRef(t)}return A},Env.prototype.getClassName=function(e){var t=t"
        "his.method(\"pointer\",[])(this.handle,e,this.javaLangClass().getName)"
        ",n=this.stringFromJni(t);return this.deleteLocalRef(t),n},Env.prototyp"
        "e.getTypeName=function(e){return this.isInstanceOf(e,this.javaLangClas"
        "s().handle)?this.getClassName(e):\"java.lang.Object\"},Env.prototype.s"
        "tringFromJni=function(e){var t=this.getStringUtfChars(e),n=Memory.read"
        "Utf8String(t);return this.releaseStringUtfChars(e,t),n}}();var getApi="
        "function(){if(null!==_api)return _api;var e={},t=[{module:\"libdvm.so"
        "\",functions:{_Z20dvmDecodeIndirectRefP6ThreadP8_jobject:[\"dvmDecodeI"
        "ndirectRef\",\"pointer\",[\"pointer\",\"pointer\"]],_Z15dvmUseJNIBridg"
        "eP6MethodPv:[\"dvmUseJNIBridge\",\"void\",[\"pointer\",\"pointer\"]]},"
        "variables:{gDvmJni:function(e){this.gDvmJni=e}}}],n=0;return t.forEach"
        "(function(t){var r=t.functions,a=t.variables;n+=Object.keys(r).length+"
        "Object.keys(a).length,Module.enumerateExports(t.module,{onMatch:functi"
        "on(t){var i=t.name;if(\"function\"===t.type){var o=r[i];o&&(\"function"
        "\"==typeof o?o.call(e,t.address):e[o[0]]=new NativeFunction(t.address,"
        "o[1],o[2]),delete r[i],n--)}else if(\"variable\"===t.type){var l=a[i];"
        "l&&(l.call(e,t.address),delete a[i],n--)}return 0===n?\"stop\":void 0}"
        ",onComplete:function(){}})}),0===n&&(_api=e),_api},checkJniResult=func"
        "tion(e,t){if(t!=JNI_OK)throw new Error(e+\" failed: \"+t)},basename=fu"
        "nction(e){return e.slice(e.lastIndexOf(\".\")+1)}}.call(this);",
